### ISSUE TITLE
Byte decoding issue in newest version?

### ISSUE THREAD

**Issue by jj98594** [woj-ciech/LeakLooker#17]
Traceback (most recent call last):
  File "leaklooker.py", line 553, in <module>
    listing_results = binaryedge_query(listing_query + " " + query,page)
  File "leaklooker.py", line 248, in binaryedge_query
    req_json = json.loads(req.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by raditya69** [comment]
i already struggling with this

**Comment by jj98594** [comment]
This was solved by updating to Python 3.6 but it looke like BinaryEdge changed something. I'll open a new issue for that.
